version: '3.8'
services:
  sharing-session-api:
    image: ghcr.io/thinc-org/react-sharing-session-api-2022:main
    container_name: sharing-session-api
    restart: always
    networks:
      - traefik-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.sharing-session-api.rule=Host(`sharing-session-api.thinc.in.th`)
      - traefik.http.routers.sharing-session-api.tls=true
      - traefik.http.routers.sharing-session-api.tls.certresolver=letsencrypt
  sharing-session:
    image: ghcr.io/thinc-org/react-sharing-session-2022:main
    container_name: sharing-session
    restart: always
    networks:
      - traefik-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.sharing-session.rule=Host(`sharing-session.thinc.in.th`)
      - traefik.http.routers.sharing-session.tls=true
      - traefik.http.routers.sharing-session.tls.certresolver=letsencrypt

networks:
  traefik-net:
    external: true