apiVersion: v1
kind: Service
metadata:
  name: sharing-session-api
spec:
  selector:
    app: sharing-session-api
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
