apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-act-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-act-api
  template:
    metadata:
      labels:
        app: first-act-api
    spec:
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      containers:
        - name: first-act-api
          image: ghcr.io/thinc-org/first-act-frontend-api-2022:main
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 50m
              memory: 150Mi
            limits:
              cpu: 300m
              memory: 300Mi
